### PR TITLE
Partial rewrite

### PR DESCRIPTION
**Pull request by lrnv**
Hey, 

I took a first shot at a partial rewrite. Basically: 

- In Julia, the standard way to do things is to use types, multiple dispatch, and pass objects around instead of only values. 
- If statements are better handled at compile time by the compiler
- You had a lot of redundant code. 
- `Distributions.jl` already implements a bunch of things for distributions, no need to reinvent the wheel. See there for the full API : https://juliastats.org/Distributions.jl/latest/extends/#Univariate-Distribution

I was going to try it, but then realize you do not have tests implemented for your functions... So take this with a grain of salt until we have proper benchmark to see if my code actually runs like yours did or not. 

There is potential for more improvements, but until a proper test suite is in place this is difficult to understand what you really want to do with it :)

Tell me what you think and/or provide me a testing use case if you want me to dig a bit more around.

### CODE REVIEW

**Comment by FJRubio67** [comment]
Hi Oskar,

Thank you for your comments and the proposed changes.

I started this project as a learning exercise as I just started programming in Julia in the last couple of months. I decided to translate one of my R packages (HazReg). As you can see, my programming proficiency in Julia (and in general :D ) is not that great. This being said, I think the package has potential to be applicable in real data, as the models go beyond the sempiternal proportional hazards model.

I agree with your points 1-3. I was aware the implementation was suboptimal, but I was not clear how to do it using structures. So, I left this part for the future.  Regarding point 4, I know many things are already implemented for common distributions, but hazard functions do not seem to be one of them, specially for the less common distributions such as GenGamma, PGW, and EW.

Indeed, one of the limitations in the first release is the lack of formal tests. However, I "informally" tested the functions in the real data applications (where I basically used and tested/used all functions).

So, there are still quite a few things to improve in the package. Now, my questions are:

1. Are you interested in doing a more substantial contribution to the package? If so, you would be properly acknowledged.
2. Could you check if you can reproduce the results in (https://fjrubio.quarto.pub/hazregjulia/) after your rewrite?

No worries if you do not have time or interest, just checking how far you want to go with this. If yes, we can explore other possible extensions (e.g. multivariate survival, I was aware of your package on copulas). If not, I will try to allocate some time to include formal tests to evaluate your changes and later approve the merge pull request.

I look forward to hearing from you.

Best,
Javier.

**Comment by lrnv** [comment]
Hey, 

I understood that you are a beginner in Julia, my goal was simply to help you out: there are a lot of conventions and habits in the Julia world that are absolutely necessary for efficiency but hard to grasp before you confronted them :). I do care about the subject, indeed there are potential real data applications, which is why I thought I'll help you out. 

`Distributions.jl` provides a wonderful API. Indeed, it does not include log hazard / hazard / cumulative hazard, but if you look at my PR, adding those to ALL distributions was only three lines of code due to the type system. If you want exotic distributions then adding them is a bit more work but nothing compared to what you previously had (there might even be some "powering of a dist" mechanism inside Distributions.jl, but I am not sure). If for some distributions you lack performance, things can be refined later: the beauty of multiple dispatch. 

Yes, I will definitively try to reproduce your results whenever I have some time (might not be right now). Basically, these results should be turned into tests, so that we are sure we reproduce them whatever change we make to the code. 

I am not sure of the bandwidth i have to commit to this project, but I'll be definitely interested into multivariate stuff and dependence structures, for sure.

**Comment by FJRubio67** [comment]
Excellent. Thank you very much for your suggestions and contributions. Let me know if there is anything I can help with to facilitate this. 

Indeed, the suggested change using the `Distributions.jl` package will generalise the package widely. 

No rush or pressure on my side. I think there is a nice opportunity to build up the package. I can later tell you of another generalisation that we could consider, and that would allow us to consider a wide range of multivariate survival models (such contribution could be beyond the Julia package).

Best,
Javier.

**Comment by lrnv** [comment]
haaaaaaaa !!! WHy did you merge this one ?? ^^

Was not finished AT ALL ^^

**Comment by lrnv** [comment]
There should be a "revert" button here

**Pull request merged**
